nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin:
      - 'http://localhost:4200'
      - 'http://127.0.0.1:4200'
      - 'http://localhost:50030'   
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['Link', 'Authorization']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    max_age: 3600
    origin_regex: false
  paths:
    '^/api/': ~